### ISSUE TITLE
support saving images as jpg also

### ISSUE THREAD

**Issue by stepheneb** [concord-consortium/shutterbug#1]
I took a couple of snapshots from http://lab.dev.concord.org/interactives.html with the Interactive rendered at a large size and saved them locally.

jpg versions appear to be about 25% of the size of a png version

Here's the difference in sizes for the original png and a jpg version saved at 60% quality setting:

    127K ae60661dc80.png
     32K ae60661dc80.jpg
    
    168K b1c1b503128.png
     46K b1c1b503128.jpg

The quality of the jpg images looked fine on a quick inspection.

**Comment by pjanik** [comment]
It has been implemented recently:
https://github.com/concord-consortium/shutterbug.js#basic-usage
